### ISSUE TITLE
Is implementation of full material-design guidelines your mission?

### ISSUE THREAD

**Issue by atotic** [PolymerElements/paper-elements#46]
Is paper-elements mission to implement full material-design guidelines? There is still a lot of low-hanging fruit not getting implemented.

If not, you should solicit community contributions for "elements you are not doing", so we are not all doing silly things like this:

```
 Polymer({

    is: 'paper-bottom-sheet',

    properties: {
      animationConfig: {
        value: function() {
          return {
            'entry': {
              name: 'slide-from-bottom-animation',
              timing: {
                duration: 250
              },
              node: this
            },
            'exit': {
              name: 'slide-to-bottom-animation',
              timing: {
                duration: 100
              },
              node: this
            }
          }
        }
      },
      withBackdrop: {
        type: Boolean,
        value: true
      }
    },

    behaviors: [
      Polymer.PaperDialogBehavior,
      Polymer.NeonAnimationRunnerBehavior
    ],

    listeners: {
      'neon-animation-finish': '_onNeonAnimationFinish'
    },

    _renderOpened: function() {
      if (this.withBackdrop) {
        this.backdropElement.open();
      }
      this.playAnimation('entry');
    },

    _renderClosed: function() {
      if (this.withBackdrop) {
        this.backdropElement.close();
      }
      this.playAnimation('exit');
    },

    _onNeonAnimationFinish: function() {
      if (this.opened) {
        this._finishRenderOpened();
      } else {
        this._finishRenderClosed();
      }
    }
```

**Comment by tjsavage** [comment]
Full material-design guidelines is a moving target, so with the paper-elements we try to maintain the full set of primitives that can be composed to build material-design-y apps and components.  The goal is to nail the hard parts of material design like ripples, animations, etc. so that the easy things in material design are easy to build. Directly because elements like `paper-bottom-sheet` are low-hanging fruit make them lower-priority for us to implement and maintain. 

Good point, it would help to have them somewhere on the roadmap to better answer the question "should I build this myself." We'll likely build out to support these simpler elements in the mid-term.
