### ISSUE TITLE
Properties not cleared when elements reused in dom-repeat. 

### ISSUE THREAD

**Issue by kayur** [PolymerElements/paper-elements#62]
I'm trying to use dom-repeat to create a list of paper buttons, which have a custom attribute that I set. The html template for the custom element is a bit complicated but here is an example that illustrates the core issue:

```
<dom-module id="my-element">
  <template>
    <template is="dom-repeat" items="[[experiments]]">
      <paper-button label$="[[item.name]]">
        [[item.name]] the [[item.job]]
      </paper-button>
    </template>
  </template>
  ...
```

`<my-element>` has an property `experiments` which gets updated frequently with new data. `experiments` is used to generate a list of `<paper-button>` with a custom attribute `label` that's set to `item.name`.

Let's set `experiments = [{ name: "joe", job: "plumber"}, { name: "cat", job: "maker"}]`

Let's call the first paper button, `button`. I would expect `button.getAttribute(label) === joe` and `button.label === undefined`. That's not the case. Some magic sets `button.label` to `joe`. That's fine. It could be useful magic. 

Now let's set `experiments = [{name: "cat", job: "maker"}]`. I would expect `button.getAttribute(label) === cat`, and indeed that's correct. But `button.label === joe`. 

Why is this happening? 

It feels like a bug because I'd expect reused elements not have zero state that indicates they were used for anything else before.

Here is a jsbin with this example: 
http://jsbin.com/hetazocaye/6/edit?html,js,console,output

Strangely div does the right thing. 
http://jsbin.com/rekavifozu/3/edit?html,js,console,output

**Comment by kevinpschaaf** [comment]
Yes, this looks like a bug with the data configuration process Polymer uses to efficiently flow binding data to other Polymer elements at initial construction of the tree.  It incorrectly passes attribute bindings as property data.  This should be trivial to fix, such that the label property is always `undefined` in your `paper-button` example: http://jsbin.com/gonola/edit?html,console -- I assume this is what you would expect, yes?

**Comment by kevinpschaaf** [comment]
This issue was moved to Polymer/polymer#3288

**Comment by sjmiles** [comment]
>> Some magic sets button.label to joe. That's fine. It could be useful magic.

This is actually the core of the problem. You have specifically bound to the label _attribute_ via `$` here `<paper-button label$="[[item.name]]">` and it should not be affecting the label _property_.

I looks like the property is being set because of a bug in Polymer code that optimizes performance of element creation. Its only set the one time because the bug is only in the creation code, and when the element is re-used it doesn't take that code path.

Although it's still a bug, normally this would be harmless, since no agent has any actual interest in the label property.

I'll follow up with an issue ticket.
